#!C:\Users\Owner\NEEA\alex_neea_flex_load_26\OCHRE\OCHRE Regulation\OCHRE in Excel\.venv-hpwh\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
